#!/usr/bin/env bash

# Alex's brewfile

# Install Homebrew packages
brew 'caskroom/cask/brew-cask'
brew 'bash-completion'
brew 'git'
brew 'imagemagick'
brew 'macvim'
brew 'node'
brew 'phantomjs'
brew 'python3'
brew 'shellcheck' # Used by SublimeLinter-shellcheck
brew 'spotify'

# Install Cask Apps
cask 'sublime-text'
